export const PLATFORM_ERROR_CODES = {
  RESOURCE_CONFLICT: 'PLATFORM.RESOURCE_CONFLICT',
  NOT_FOUND: 'PLATFORM.NOT_FOUND',
  VALIDATION_ERROR: 'PLATFORM.VALIDATION_ERROR',
  UNAUTHORIZED: 'PLATFORM.UNAUTHORIZED',
  INTERNAL_ERROR: 'PLATFORM.INTERNAL_ERROR',
} as const;

export type PlatformErrorCode = (typeof PLATFORM_ERROR_CODES)[keyof typeof PLATFORM_ERROR_CODES];
